### PR TITLE
Mod downloads

### LINKED ISSUE #959: Remove "mod downloads" counter

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #959

### CODE REVIEW

**Comment by Brutus5000** [comment]
This PR is having a major quality issue. The naming doesn't tell what it does. The commit claims to fix an issue but instead it just removes the feature. This should not be the way to go.

**Comment by 1-alex98** [comment]
Well I found out that there is no data in the database that could tellus how many installations there are so I asked downlord whether to remove it then

**Comment by Brutus5000** [comment]
That is totally okay, but then put this text into the issue and also in the PR description!

**Comment by 1-alex98** [comment]
Yeah i am sorry I should have provided more information ;)

**Review by micheljung — APPROVED** [review]

**Pull request merged**
