### PR TITLE
On pre-release channel, just take the highest release

### LINKED ISSUE #1962: Final releases are ignored in pre-release channel
**Describe the bug**
Once you opt-in for pre-releases the update notification only ever works for pre-releases.

### PR DESCRIPTION
**Pull request by Brutus5000**
fixes #1962

### CODE REVIEW

**Comment by Sheikah45** [comment]
Would this cause update notifications on non pre-release and non official releases as well?

**Comment by 1-alex98** [comment]
Then @micheljung should probably stop calling this releases v1.3.0-RC1 and so on.

**Review by 1-alex98 — APPROVED** [review]

**Comment by 1-alex98** [comment]
@Sheikah45 u mean drafts? They are not seen for none developers anyways

**Comment by micheljung** [comment]
> Then @micheljung should probably stop calling this releases v1.3.0-RC1 and so on.

what?

**Comment by 1-alex98** [comment]
U made prereleases called v1.3.0 right? They are gonna shadow all other releases/prereleases then

**Comment by Brutus5000** [comment]
> Would this cause update notifications on non pre-release and non official releases as well?

Only if the tag name follows the semver pattern and only if it is a higher semver-number.


> U made prereleases called v1.3.0 right? They are gonna shadow all other releases/prereleases then

That is already the case. It pulls the highest release and checks for pre-release flag.

**Comment by Sheikah45** [comment]
I meant the releases that are being done for the auto update testing. And currently I don't get notified about those

**Comment by 1-alex98** [comment]
> I meant the releases that are being done for the auto update testing. And currently I don't get notified about those

Probably cause they don't have an exe

**Comment by Brutus5000** [comment]
According to Zulip chat people already got the notification for 1.3.0-RCxx and downloaded it already.

**Comment by 1-alex98** [comment]
Yes but with this request Downlord 1.30 will shadow our new prereleases forever XD we will need to delete those

**Review by 1-alex98 — APPROVED** [review]

**Pull request merged**
