### PR TITLE
Rework of sub-tabs II

### PR DESCRIPTION
**Pull request by BlackYps**
We found bugs in the already merged PR #1715 , so we had to revert it.
Here is the fixed version.

### CODE REVIEW

**Comment by 1-alex98** [comment]
naming schema for branches feature/#1715-rework-new-sub-tabs

**Comment by 1-alex98** [comment]
Might be that this happens in a different PR that I alredy merged from you, but now the client log is spammed with warning about broken css:
```
2020-05-25 18:28:30.902  WARN 7552 --- [lication Thread] javafx.css                               : Could not resolve '-fx-text-base-color' while resolving lookups for '-fx-text-fill' from rule '*.label' in stylesheet file:/C:/Users/Alexander/IdeaProjects/downlords-faf-client-2/out/production/resources/theme/style.css
``` 
and others as well:
```
2020-05-25 18:28:30.880  WARN 7552 --- [lication Thread] javafx.css                               : Caught 'java.lang.ClassCastException: class java.lang.String cannot be cast to class javafx.scene.paint.Paint (java.lang.String is in module java.base of loader 'bootstrap'; javafx.scene.paint.Paint is in unnamed module of loader 'app')' while converting value for '-fx-background-color' from rule '*.card' in stylesheet file:/C:/Users/Alexander/IdeaProjects/downlords-faf-client-2/out/production/resources/theme/style.css
```

**Review by 1-alex98 — CHANGES_REQUESTED** [review]
see above

**Comment by BlackYps** [comment]
Are you sure that you have looked at an up-to-date log? Seems like the client appends the log file everytime and the first time I could indeed find these errors. I then cleared the log file and now I can't trigger the warnings...

**Comment by 1-alex98** [comment]
I am sure I ran an up to date version

**Comment by BlackYps** [comment]
I see lots of these
`2020-05-25 22:06:04.313  WARN 4208 --- [JavaFX Application Thread] javafx                                   : Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 10.0.2-internal`
but none of the mentioned css errors. Can you tell me what you do to produce the css warnings?
And please don't say "I click random tabs in the client", because I do that ^^

**Comment by Katharsas** [comment]
I got tons of random CSS warnings some months ago which could only be reproduced sometimes.

**Comment by 1-alex98** [comment]
Lemme us check together one day

**Comment by 1-alex98** [comment]
open the play tab

**Pull request merged**
