### PR TITLE
Show playtime of live game

### LINKED ISSUE #2036: Show playtime of live games
iirc on the legacy client you could check how long someone elses current game has been going on for. You usually use this when deciding to wait for some friends to finish their game before you start one yourself, or to continue playing if you see they only just started a new game.

As far as i've seen this doesn't exist in  the java client? Atleast i haven't found it hovering my cursor over the sword- or map icon gives no popup that might give info and there is no info here either:
downlords-faf-client_Mc1B9w9dK5

I tried to look in the live replays and did find it after some time of looking but it is really hard to search for a particular game in there.

So a couple  of ideas would be:
 - A popup that shows info when your cursor hovers over the sword/map icons in the chatlist
 - When you are in a pm with someone the current game info on the right side could include some timer for how long the game has been going on
 - Some way to make it quicker to find friends in the live replay list: Maybe a searchbar, maybe a checkbox with "friends only", maybe something similar as what the legacy client had which made games with friends stand out by marking them as blue i believe.

### PR DESCRIPTION
**Pull request by Marc-Spector**
Closes #2036 

image

### CODE REVIEW

**Comment by Marc-Spector** [comment]
Changes to `GameDetailController` class are made in order to avoid errors related to the unsynchronized `game` variable
Some errors that occur in production version of client:
```
ERROR 13200 --- [JavaFX Application Thread] c.f.c.exception.GlobalExceptionHandler   : Uncaught exception on Thread[JavaFX Application Thread,5,main]: 

java.lang.NullPointerException: Cannot invoke "com.faforever.client.domain.GameBean.getNumPlayers()" because "this.game" is null
	at com.faforever.client.game.GameDetailController.lambda$onNumPlayersChanged$4(GameDetailController.java:107)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

```
java.lang.IllegalArgumentException: The game's start must not be null: GameBean(title=+1000, id=17563001, status=OPEN)
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at com.faforever.client.vault.replay.WatchButtonController.setGame(WatchButtonController.java:66)
	at com.faforever.client.game.GameDetailController.lambda$onStartTimeChanged$11(GameDetailController.java:153)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Sheikah45** [comment]
Haven't looked at the code yet but I think it might be better if the playtime was in the section beneath the map as currently it almost looks like a stat for the player since that info is above the map. 

Maybe better somewhere near the watch button or integrated to the watch button.

**Comment by Marc-Spector** [comment]
Ok

**Comment by Marc-Spector** [comment]
image

**Review by Sheikah45 — APPROVED** [review]

**Pull request merged**
