### PR TITLE
Init ladder queue time

### LINKED ISSUE #1466: Implement initial matchmaker_info request
Related to #1361 
Allows pop time queue to be shown immediately.
Requires https://github.com/FAForever/server/pull/489

### PR DESCRIPTION
**Pull request by Katharsas**
Fixes #1466

### CODE REVIEW

**Review by 1-alex98 — COMMENTED** [review]
I can test this on prod?

**Comment by Katharsas** [comment]
No, see issue for required server changes.

**Review by Geosearchef — DISMISSED** [review]

**Comment by Katharsas** [comment]
Works on test.

**Comment by 1-alex98** [comment]
@Askaholic did we deployed the needed server change for this

**Comment by Askaholic** [comment]
@axel1200 No it is not deployed yet. It's commit https://github.com/FAForever/server/commit/cc8030143a24b335d3682fa5a0cf69207454738b

**Comment by Askaholic** [comment]
This change has been deployed in [FAForever/server - v1.3](https://github.com/FAForever/server/tree/v1.3.1).

**Comment by 1-alex98** [comment]
Is it still deployed with all this everting back to old versions

**Comment by Askaholic** [comment]
You're right. It has been rolled back. I'll comment again when I fix the server issues for good.

**Comment by Katharsas** [comment]
Rebased to fix merge conflicts.

**Comment by Askaholic** [comment]
BTW this is deployed now, although I think ideally we would send the message after login and the client would just not throw it away. Leave it sitting in a message queue somewhere until the ladder tab is opened.

**Comment by 1-alex98** [comment]
So should I test or merge or not?

**Comment by Katharsas** [comment]
@Askaholic 
I think this being implemented as a request (like it is right now) is more flexible and, less complex and less error prone.  For example it would allow the client to close & unload the ladder tab and then resend the request to recreate it when needed instead of it always existing.

I see no reason why this information being sent should be specifically bound to login time and why the client should not have the freedom to ask  for it whenever it wants.

**Comment by Askaholic** [comment]
The thing is I'm not a big fan of adding server (and protocol) complexity just for convenience in the client implementation. I'd rather send it at login so it works just like the game list and just like the player list. The client can load and unload the ladder tab all it wants, the queue pop time will be the same until the server sends a new info message. 

It feels like we're letting the client implementation intrude into the protocol by doing this. We're not adding this message because it makes sense for the protocol. Obviously it's not a huge complexity, but it's something that will build up over time, and once it's added it gets very hard to remove.

**Comment by Katharsas** [comment]
With "unloading" i mean forgetting everything about ladder state and having to reinitialize that information from the server.

I guess I just dislike the general protocol architecture then (im used to web world, where generally the client requests what it wants and the server is mostly just a dumb state store, which works generally quite well but is of course very different). But it makes sense that you want to keep the protocol consistent.

**Comment by 1-alex98** [comment]
ok an this means for me ?

**Comment by Katharsas** [comment]
Merge. Can still be changed later if somebody wants to build a message queue.

**Review by 1-alex98 — APPROVED** [review]

**Comment by 1-alex98** [comment]
Merging if test run through

**Pull request merged**
