### PR TITLE
Remove friend and foe icons and replace them with a background

### PR DESCRIPTION
**Pull request by Marc-Spector**
Makes the design cleaner.

You can close the pull request if you think there is no reason to update the design.

image

### CODE REVIEW

**Comment by Sheikah45** [comment]
Probably would be good to keep the icons for people who are red green colorblind

**Comment by Askaholic** [comment]
I think there still needs to be something other than the color that shows who is a friend and who is a foe. Especially considering that red-green colorblindness is the most common form of colorblindness.

**Comment by Brutus5000** [comment]
How about bold or underlined for friend and strikethrough for foe

**Comment by Marc-Spector** [comment]
Maybe add the option "Colorblind mode" in the settings of the client?

**Comment by Marc-Spector** [comment]
> How about bold or underlined for friend and strikethrough for foe

Nooo, it is even worse than icons. 😄

**Comment by ghost** [comment]
Just color the text. Bg should be clear :P

**Comment by Sheikah45** [comment]
For now I think the icons are better than the color background in terms of visibility

**Pull request closed without merging**
