### PR TITLE
Write to an advanced log

### LINKED ISSUE #1431: Add an option to log stdout and stderr of the adapter
[Issuehunt badges](https://issuehunt.io/r/FAForever/downlords-faf-client/issues/1431)

Not everything from the ice adapter is logged to its own log. This is needed for investigating most adapter issues. Please add an option in the settings that enables logging stdout and stderr of the adapter process to the client log.

Basically, revert https://github.com/FAForever/downlords-faf-client/commit/4f695052b67a1a0697f34cc9351b18d3387fcbb9 based on an option and make sure the log level is correct.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [geosearchef geosearchef](https://issuehunt.io/u/geosearchef) ($5.00)
### Submitted pull Requests
- [#1468 Write to an advanced log (LOGBACK)](https://issuehunt.io/r/FAForever/downlords-faf-client/pull/1468)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/FAForever/downlords-faf-client/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #1431

### CODE REVIEW

**Review by Geosearchef — COMMENTED** [review]
Do we want to always write this log? I'd create an option for the user to tick in the settings menu.

**Comment by 1-alex98** [comment]
Well i would always write it, it is not that big and I delete old version so does not really take disk space.

And lets say something happens that is not reproducable u be happy that it was turned on ;)

**Review by Geosearchef — APPROVED** [review]

**Comment by Geosearchef** [comment]
It can produce a lot of data though

**Comment by 1-alex98** [comment]
U tell me what u want, I mean I am not an expert on this. Well what i can do is only write STDERR that will make it become pretty small . I mean STDOUT is not really interesting anyway right?
Because that is written to standard ice adapter log anyway right

**Comment by 1-alex98** [comment]
@Geosearchef u here?

**Comment by 1-alex98** [comment]
what did we agree on in the end?

**Comment by 1-alex98** [comment]
Do u want to add option to disable ice adapter log itself?

**Comment by Geosearchef** [comment]
An option to disable it doesn't make a lot of sense, only one to enable it does.

**Comment by 1-alex98** [comment]
yeah sure

**Comment by Katharsas** [comment]
Btw @axel1200 dont let the other PR stop you from implementing the GUI option, i can always ~~steal~~ move your commits xD

**Pull request closed without merging**
