### PR TITLE
Modification of the client in order to transfer the parameters of the avatar in the game lobby.

### PR DESCRIPTION
**Pull request by GodFuper**
Adaptation to avatar in the lobby. Lobby will use name.png avatars.

### CODE REVIEW

**Comment by GodFuper** [comment]
Client+ lobby "https://github.com/FAForever/fa/pull/2519"

**Comment by Brutus5000** [comment]
Dear Super4121,

thank your for your support. Since this is your first contribution in this repository I may give you some advice. If you think you are done and want a review of your work, please add the label "ready to be merged". Otherwise keep "in progress".
To understand changes our git log in the future we always open an issue (in your case i.e. "Support avatars in game lobby" and reference that issues in the commit message (i.e. Stores avatar files on disk with consistent naming (fixes #xxx) )

In your special case you may want to squash the many commits into one, since only few files are touched. This can be done with an "interactive rebase" ending with a force push on this branch. More information can be found here: https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Comment by Geosearchef** [comment]
Please use "full names" for variables in this project, therefore rename e. g. `nameAva` to `nameAvatar`.

Also instead of squashing commits you can SOFT reset back onto the commit before your commits, your changes will still be there and you can then recommit them and force push that single commit afterwards.

**Comment by GodFuper** [comment]
I don't know how to add a Label.

**Comment by axel1200** [comment]
You can not you need to be made contributer by @micheljung

**Comment by 1-alex98** [comment]
Please make all those commit one commit, with format:

-Title-
-blank line-
-Further description-
Fixes #943 

By either rebasing and squashing commit or by resetting branch(soft) and adding new commit(force push)

**Comment by 1-alex98** [comment]
There are security concerns about that people could manipulate their avatar. We could only rule them out if game asked the server/its own client (for every player) right?

**Pull request closed without merging**
