### PR TITLE
Context menu of the player in sidebar of the game information

### LINKED ISSUE #2301: Open a private channel by double clicking on the desired player in the sidebar of the game information.
There are cases that the player for some reason missed the notification that the game is full.
The host needs to perform additional actions such as:
1) Open the "Chat" tab (and open the #aeolus channel if it is not open)
2) Find a player
3) Open a private channel
4) Write a message

### LINKED ISSUE #2325: Add context menu for each player in the sidebar of the game information

### PR DESCRIPTION
**Pull request by Marc-Spector**
Closes #2325 
Closes #2301

### CODE REVIEW

**Comment by Marc-Spector** [comment]
@Sheikah45 You do not know where the button like "The PR is ready for review"?

**Comment by Sheikah45** [comment]
I don't know what you mean. That button only appears if you made a draft PR initially. but this isn't a draft pr

**Comment by Marc-Spector** [comment]
Oh I mean ask the reviewers to review my pull request

**Comment by Sheikah45** [comment]
Oh you didn't have write access. I gave it to you so you should now be able to request review in the top right once you accept

**Comment by Marc-Spector** [comment]
@Sheikah45 Good. Thank you!

**Review by Sheikah45 — CHANGES_REQUESTED** [review]
Rather than create a new fxml file and view it would be better to just reuse the chatUserContextMenu as almost all of the options are the same. And there isn't really a reason to leave out the ones specifically removed here.

**Pull request closed without merging**
