### PR TITLE
Change library for isWindows() calls

### LINKED ISSUE #1333: Client fails to start on non-latin named user accounts (platform windows)
```
java.lang.UnsatisfiedLinkError: org.bridj.Platform.sizeOf_ptrdiff_t()I
	at org.bridj.Platform.sizeOf_ptrdiff_t(Native Method)
	at org.bridj.Platform.<clinit>(Platform.java:232)
	at com.faforever.client.preferences.PreferencesService.<clinit>(PreferencesService.java:78)
	at com.faforever.client.FafClientApplication.main(FafClientApplication.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
```

### PR DESCRIPTION
**Pull request by 1-alex98**
Fix #1333

### CODE REVIEW

**Comment by 1-alex98** [comment]
Locally everthing bilds fine but travis had some native crash. Maybe somebody with an linux set up can run the tests on his machine

**Review by Brutus5000 — CHANGES_REQUESTED** [review]
The inconsequent use of static import vs fully qualified reference vs partially qualified references makes me cringe. Let's fix that as well.

**Comment by 1-alex98** [comment]
Please tell me how to. The strategy here is use static import if u can and not if u can not. All I did was replace the old stuff by new library

**Review by Katharsas — APPROVED** [review]

**Comment by norraxx** [comment]
Are we sure for merge?

Fails now on:
```
 if (com.sun.jna.Platform.isWindows()) {
      FAF_DATA_DIRECTORY = Paths.get(Shell32Util.getFolderPath(ShlObj.CSIDL_COMMON_APPDATA), "FAForever");
    }
```

Problem is system class loader:
see more info on Java Native Access library pages:
https://github.com/java-native-access/jna/issues/124
https://github.com/java-native-access/jna/issues/238
https://bugs.openjdk.java.net/browse/JDK-8017274


We talk to disable client on non-ascii usernames.

**Pull request closed without merging**
