### PR TITLE
server oauth

### PR DESCRIPTION
**Pull request by 1-alex98**
WIP
Relates to #1533

### CODE REVIEW

**Comment by 1-alex98** [comment]
Really need to pick this up again

**Comment by Sheikah45** [comment]
Is this testable on prod or the test server?

**Comment by 1-alex98** [comment]
u need to ask @Askaholic but I am pretty sure it is a little buggy

**Comment by 1-alex98** [comment]
The answer will be no https://github.com/FAForever/server/pull/591
You will need to deploy the PR on test which is not the easiest thing to do cause you also need to make the required config changes

**Comment by 1-alex98** [comment]
Maybe I can help you some day or @Askaholic

**Comment by Sheikah45** [comment]
Going to combine with #2175

**Comment by Sheikah45** [comment]
superceded by #2175

**Pull request closed without merging**
