### PR TITLE
#1781, #1782, #1694 Map Generation Options and UI enhancements

### PR DESCRIPTION
**Pull request by Sheikah45**
Connected to FAForever/Neroxis-Map-Generator#37, #1781, #1782, #1694. This pull request creates an interface and backend for map generation with options. A new dialog window is created when the generate map button is pressed for inputing either a map name to recreate or options to generate a new map with.

On the back end generated map names are generated as neroxis_map_generator_(version)_(seed)_(options) and passed to the generator jar file. seed and options are base64 encoded strings and encoding is done in the client prior to sending. It should be noted that these map names will not be parsable by older java clients.

The map generator service map name validation was changed to recognize both the old generated names as well as new and hopefully has enough flexibility to absorb future changes.

### CODE REVIEW

**Comment by Katharsas** [comment]
Don't change any language files except the english one. Other translations will be completed by translators via a crowdsourcing portal.

**Comment by Sheikah45** [comment]
I can change back the other language files although it looks like the change is just a change of the variable names that happened when I changed some of the message.properties variable names and intellij refactored them. But if that is an issue I can change them back.

**Comment by Katharsas** [comment]
Oh ok well im not sure then, @axel1200 what do you think?

**Comment by 1-alex98** [comment]
Remember me to have a look at this

**Comment by micheljung** [comment]
Thanks for contributing! Please make sure to follow [The seven rules of a great Git commit message](http://chris.beams.io/posts/git-commit/#seven-rules).

**Comment by Sheikah45** [comment]
Closed due to bad branch history opening new pr with corrected history

**Comment by Katharsas** [comment]
Btw. you can just force push your existing branch, PR should pick it up.

**Pull request closed without merging**
