### PR TITLE
Fix disappearance of players in the team list

### LINKED ISSUE #2678: A random player disappears from the team list
**Describe the bug**
In the details of the game, a random player disappears from the team list. The number of players in the lobby does not change. There's nothing wrong with the player in the lobby.

**To Reproduce**
Don't know.

**Log or error message**
No any error messages in log file.

**Expected behavior**
Return the player to the team list.

**Screenshots**
image

**OS**
Windows

Client Version: 2022.4.0-alpha0

### PR DESCRIPTION
**Pull request by Marc-Spector**
Closes #2678 

It happens when the player leaves `#aeolus` channel

### CODE REVIEW

**Comment by Marc-Spector** [comment]
I see no reason to remove players from the map. It won't get any worse.

**Comment by Marc-Spector** [comment]
damn it...

**Comment by Sheikah45** [comment]
Wouldn't this potentially lead to a memory leak as players are only added and never removed from the map?

**Comment by Marc-Spector** [comment]
It's possible. I need to find another solution. My change is not suitable as it breaks a notification that a friend has logged into the client.

**Review by Sheikah45 — APPROVED** [review]

**Pull request merged**
