### PR TITLE
Make all joined attributes not sortable

### LINKED ISSUE #1901: Error accessing replays in the vault
I search for replays with values "One of the player's global ratings" "is greater than" "1500" 

I get the same errors or very similar ones with every variable i seem to enter in the vaults search functions.

I get the following error message,

java.util.concurrent.CompletionException: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: [{"errors":["InvalidValueException: Invalid value: Combination of pagination, sorting over relationship and filtering over toMany relationships unsupported"]}]
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:279)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: [{"errors":["InvalidValueException: Invalid value: Combination of pagination, sorting over relationship and filtering over toMany relationships unsupported"]}]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:101)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	at com.faforever.client.api.JsonApiErrorHandler.handleError(JsonApiErrorHandler.java:31)
	at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:177)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:132)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:315)
	at com.faforever.client.api.FafApiAccessorImpl.getPageWithMeta(FafApiAccessorImpl.java:652)
	at com.faforever.client.api.FafApiAccessorImpl.getPageWithMeta(FafApiAccessorImpl.java:627)
	at com.faforever.client.api.FafApiAccessorImpl.findReplaysByQueryWithMeta(FafApiAccessorImpl.java:336)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
	at com.sun.proxy.$Proxy69.findReplaysByQueryWithMeta(Unknown Source)
	at com.faforever.client.remote.FafService.findReplaysByQueryWithPageCount(FafService.java:320)
	at com.faforever.client.remote.FafService$$FastClassBySpringCGLIB$$6c91c77e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
	... 4 more

Screenshot (169)

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[Issue hunt](https://issuehunt.io/r/FAForever/downlords-faf-client)

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #1901

### CODE REVIEW

**Comment by 1-alex98** [comment]
@Sheikah45 gimme review

**Comment by Sheikah45** [comment]
so needy doing so now

**Review by Sheikah45 — APPROVED** [review]
This works for me was unable to generate a search that gave the join error

**Comment by Sheikah45** [comment]
pr ci fails though

**Comment by bukajsytlos** [comment]
do we really want to do that? limiting user options just for the sake of
not showing error?

**Comment by 1-alex98** [comment]
I guess, sorting is not really that powerful anyways

**Comment by 1-alex98** [comment]
I think I wanna merge this? Any objections?

**Pull request merged**
