### PR TITLE
Redesign context menu

### LINKED ISSUE #2594: Make the context menu more attractive to the user
From a freak 

image

to a beauty (include the icons)

image

### PR DESCRIPTION
**Pull request by Marc-Spector**
Closes #2594

Final View

image

### CODE REVIEW

**Comment by Marc-Spector** [comment]
I don't know how to solve with the "Color" item.

**Comment by Marc-Spector** [comment]
demo2

**Comment by BlackYps** [comment]
Nice Work! I think an exclamation mark would fit better as a report symbol. Right now it looks more like a conversation option

**Comment by Marc-Spector** [comment]
The icons of the items are updated. See the first message.

**Comment by BlackYps** [comment]
Isn't that an "i" instead of an "!"?

**Comment by Sheikah45** [comment]
The only thing I am not sure about from a UX experience is the now two clicks required to change color and inability to see the color in the menu, although I could be convinced it is worth it

**Comment by Marc-Spector** [comment]
> inability to see the color in the menu

~~Are you joking? 😏  It is impossible not to see the color in the menu.~~

I misunderstood you. I don't think this is the commonly used feature. This is my opinion.

**Comment by Marc-Spector** [comment]
> Isn't that an "i" instead of an "!"?

Oops... My mistake, I will fix it

**Comment by Marc-Spector** [comment]
image

**Comment by Sheikah45** [comment]
Ah I just realized this is introducing a new icon source. Is there any way we could use icons from our current source and method of using the svg paths? The icon svgs are in src/icomoon and the icons are from  https://icomoon.io so we could add icons to that set if needed. You can import the json file to see the available ones.

**Comment by Marc-Spector** [comment]
https://github.com/FAForever/downlords-faf-client/wiki/Adding-Icons
Maybe just add icons to icons.css and use them?

**Comment by Sheikah45** [comment]
> [FAForever/downlords-faf-client/wiki/Adding-Icons](https://github.com/FAForever/downlords-faf-client/wiki/Adding-Icons) Maybe just add icons to icons.css and use them?

That would work as well. Just want the way we set and store icons to be uniform

**Comment by Marc-Spector** [comment]
I will continue to work with the PR when #2591 will be merged

**Comment by Sheikah45** [comment]
@Marc-Spector  did you plan on continuing this?

**Comment by Marc-Spector** [comment]
Of course. When I have free time and desire. 
There are problems with icons. They look bad and scale poorly when used through style classes.

**Comment by Marc-Spector** [comment]
This problem would have been solved if we knew how to assign the size of the viewBox in css.

**Comment by Marc-Spector** [comment]
All icons taken from icomoon.
Note that not every menu item contains an icon, because the icons are poorly scaled. Maybe in the future we will find better icons and add them.

**Comment by Marc-Spector** [comment]
@Sheikah45 The PR is ready (finished)

**Comment by Marc-Spector** [comment]
I reverted `readme.md` file. I don't know why it is displayed in the `Files changed` tab

**Review by Sheikah45 — APPROVED** [review]

**Pull request merged**
