### PR TITLE
Provide reload improvements

### LINKED ISSUE #1917: Live reload in development
My dream is to not need to restart the client after a made changes. There are ways do do this. One could make some code that reloads the complete tab if clicked on play, chat etc. (only for development). Then it needs hot reload of java classes but I would already pleased if it worked only with the theme files. Since the already have a theming support we should be able to built that easily, but maybe Intelij has some functionality on its own for this maybe using that would be interesting. Also Spring has a thing called Spring Developer tools that are supposed to enable live reload, not sure of those are suitable for us. Anyways researching this topic would be interesting.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[Issue hunt](https://issuehunt.io/r/FAForever/downlords-faf-client)

### PR DESCRIPTION
**Pull request by 1-alex98**
https://youtu.be/YRedZr6zzbM

Fixes #1917

### CODE REVIEW

**Comment by 1-alex98** [comment]
So I guess I gotta fix related tests

**Comment by Sheikah45** [comment]
I am hoping to try this out today

**Comment by Sheikah45** [comment]
going to rebase this

**Comment by 1-alex98** [comment]
@Sheikah45 should we merge this? I am not sure if it works flawlessly but it should not effect production

**Comment by 1-alex98** [comment]
Maybe I should not file watch the default theme in production

**Comment by Sheikah45** [comment]
It worked okay for me for the fxml and others the css was still a little wonky but think it is worth merging as long as production doesn't break

**Review by Sheikah45 — DISMISSED** [review]

**Review by Sheikah45 — APPROVED** [review]

**Pull request merged**
