### PR TITLE
Send `match_ready` to server immediatley on `match_found` (#1783)

### PR DESCRIPTION
**Pull request by Katharsas**
Since i do not have a full local environment i can only start testing this when https://github.com/FAForever/server/pull/820 is released on test or prod.

Waiting for clarification on https://github.com/FAForever/server/issues/607#issuecomment-897205805

### CODE REVIEW

**Comment by Sheikah45** [comment]
the ready party message is already implemented. You should just use that.

**Comment by Katharsas** [comment]
But this is not the ready party message, its an entirely different thing in terms of meaning and potential evolution? I don't think those two should be mixed up.

**Comment by Sheikah45** [comment]
The new message needs to be implemented in the lobby client

**Comment by Sheikah45** [comment]
This is out of date now

**Pull request closed without merging**
