### PR TITLE
Disable download updates button on Linux

### PR DESCRIPTION
**Pull request by Brutus5000**
As long as there is no unified installer, we can't offer automatic update installation. Thus, the button was simply removed for all OS except Windows.

### CODE REVIEW

**Comment by Sheikah45** [comment]
I wonder if we should actually make use of the os spring profiles for this

**Comment by Brutus5000** [comment]
I see no benefit of this. It's not like we're replacing whole beans with different implementations. Also it sounds silly to tell the app on startup on which OS it's running on.

**Comment by Sheikah45** [comment]
I mainly bring it up because we already run the is windows check on startup and add the Linux profile based on that.

It is all done programmatically

**Comment by Brutus5000** [comment]
How would this impact the code change here?

**Comment by Sheikah45** [comment]
It would just change it from running the isWindows check to injecting the profiles and checking if linux is in the list

Also theoretically would make it easier to test as well

**Comment by Brutus5000** [comment]
In that case I'd prefer a platform bean that has methods similar to the bridge4j Platform class (isLinux, isWindows)

**Review by Sheikah45 — APPROVED** [review]

**Pull request merged**
