### PR TITLE
Sort map pool maps by size and display name

### LINKED ISSUE #2178: Sort queue map list by display name

### PR DESCRIPTION
**Pull request by Sheikah45**
Fixes #2178

### CODE REVIEW

**Review by Brutus5000 — COMMENTED** [review]
I don't it makes sense to sort on a single page? Shouldn't the sorting be on the collected result of all pages?

**Comment by Sheikah45** [comment]
This does sort on all the results because for the map pools we have to get and combine them all then the pagination is done locally on the return line of the function

**Comment by Brutus5000** [comment]
Oh so we are just faking a page result. Hmm. Weird.

**Comment by Sheikah45** [comment]
Yes it is done that way currently just because we dont show the individual rating pools and instead show them all which we can't paginate from the api.

**Pull request merged**
