### PR TITLE
Relocate "more" buttons

### LINKED ISSUE #1728: "More" Buttons in the vault are in strange positions
The "more" buttons in the map, mod, and replay vault are bound to the right edge, which looks a bit odd.
Also they are on the same height as the headlines. So especially in the replay vault you get the problem that after you looked through the list, you have to scroll up again to actually press the right button.

Example:
This button leads you to the highest rated replays:
grafik

### PR DESCRIPTION
**Pull request by BlackYps**
Fixes #1728 

Replay Vault:
grafik

Map/Mod Vault:
grafik
The button is part of the flow pane, but it looks a bit odd. If you have suggestions to improve it visually, let me know.

### CODE REVIEW

**Comment by Katharsas** [comment]
Map/Mod vault idea: Make button height as big as a tile (100%), allign it left in the tile and rename it to ">>".

**Comment by 1-alex98** [comment]
@Katharsas might look good, not sure but does in my imagination

**Comment by Katharsas** [comment]
Would work better with proper icons i guess that look like actual arrow heads.

**Comment by BlackYps** [comment]
something like this? 
grafik

**Comment by BlackYps** [comment]
This is probably better:
grafik

**Review by 1-alex98 — DISMISSED** [review]
I still need to test it before merge tho

**Comment by BlackYps** [comment]
Yeah, don't merge it yet. the new button is just a mockup, I have to implement it properly yet.

**Comment by Katharsas** [comment]
Yeah basically. I would prefer the icon to be a little bit smaller (but keep width of button) xD

**Comment by BlackYps** [comment]
grafik

**Review by 1-alex98 — CHANGES_REQUESTED** [review]
Needs more button on owned maps

**Review by 1-alex98 — APPROVED** [review]

**Pull request merged**
