### PR TITLE
Use https

### LINKED ISSUE #1407: Consistently use https
There are place in production where there is used http for content.faforever.com

### PR DESCRIPTION
**Pull request by 1-alex98**
Fix #1407

### CODE REVIEW

**Comment by Katharsas** [comment]
There are more usages of http in the other application-xxx.yaml files that i don't see a reason to not change as well. And while you are at it maybe switch the remaining two usages of http in the build.gradle and the ci scripts^^

**Comment by 1-alex98** [comment]
ehm no in test they need to stay http because often https does not work on test

**Comment by Katharsas** [comment]
application-local.yml contains for example
`http://content.faforever.com/faf/updaterNew/updates_faf_files/ForgedAlliance.exe`
and
```
vault:
    base-url: http://content.faforever.com
```
Why can these not be http?
Same goes for other yml files.

**Comment by 1-alex98** [comment]
ok true but test.faforever does not always have a working certificate

**Comment by 1-alex98** [comment]
Anything I missed? Made a project wide search

**Review by Katharsas — APPROVED** [review]
Looks good.

**Pull request merged**
