### PR TITLE
#1399 Sort games by average rating

### PR DESCRIPTION
**Pull request by Brutus5000**

### CODE REVIEW

**Review by norraxx — COMMENTED** [review]
I think, we would like to sort games not only by rating.
We have tile and table, and in table is more sorting, than only by rating.

**Comment by Brutus5000** [comment]
Hu? This adds an additional option to sort by average rating in the tile view + a new average rating column in the table view. This doesn't remove any existing sorting options.

**Review by 1-alex98 — COMMENTED** [review]
Looks good still need to test it

**Review by 1-alex98 — APPROVED** [review]

**Comment by 1-alex98** [comment]
nooooo 
XD

**Pull request merged**
