### PR TITLE
Remove faulty characters from filename

### LINKED ISSUE #614: Client throws exception on invalid characters in map names
```
java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal char <?> at index 17: astro_crater_batl?_5vs5.v0002.png
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_111]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_111]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:659) ~[na:1.8.0_111]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[na:1.8.0_111]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[na:1.8.0_111]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1595) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
Caused by: java.nio.file.InvalidPathException: Illegal char <?> at index 17: astro_crater_batl?_5vs5.v0002.png
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[na:1.8.0_111]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[na:1.8.0_111]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[na:1.8.0_111]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94) ~[na:1.8.0_111]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255) ~[na:1.8.0_111]
	at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:53) ~[na:1.8.0_111]
	at com.faforever.client.remote.AssetServiceImpl.loadAndCacheImage(AssetServiceImpl.java:51) ~[classes/:na]
	at com.faforever.client.remote.AssetServiceImpl.loadAndCacheImage(AssetServiceImpl.java:37) ~[classes/:na]
	at com.faforever.client.map.MapServiceImpl.loadPreview(MapServiceImpl.java:327) ~[classes/:na]
	at com.faforever.client.map.MapServiceImpl.loadPreview(MapServiceImpl.java:323) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333) ~[spring-aop-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:345) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:408) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:327) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.6.RELEASE.jar:4.3.6.RELEASE]
	at com.sun.proxy.$Proxy75.loadPreview(Unknown Source) ~[na:na]
	at com.faforever.client.map.MapCardController.setMap(MapCardController.java:79) ~[classes/:na]
	at com.faforever.client.map.MapVaultController.lambda$appendSearchResult$13(MapVaultController.java:272) ~[classes/:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_111]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[na:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_111]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_111]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747) ~[na:1.8.0_111]
	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721) ~[na:1.8.0_111]
	at java.util.stream.AbstractTask.compute(AbstractTask.java:316) ~[na:1.8.0_111]
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) ~[na:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_111]
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190) ~[na:1.8.0_111]
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879) ~[na:1.8.0_111]
	at java.util.concurrent.ForkJoinPool.externalHelpComplete(ForkJoinPool.java:2467) ~[na:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.externalAwaitDone(ForkJoinTask.java:324) ~[na:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:405) ~[na:1.8.0_111]
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734) ~[na:1.8.0_111]
	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714) ~[na:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[na:1.8.0_111]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_111]
	at com.faforever.client.map.MapVaultController.appendSearchResult(MapVaultController.java:275) ~[classes/:na]
	at com.faforever.client.map.MapVaultController.replaceSearchResult(MapVaultController.java:159) ~[classes/:na]
	at com.faforever.client.map.MapVaultController.lambda$displayShowroomMaps$5(MapVaultController.java:149) ~[classes/:na]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[na:1.8.0_111]
	... 6 common frames omitted```

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #614

### CODE REVIEW

**Review by Geosearchef — APPROVED** [review]

**Review by Brutus5000 — CHANGES_REQUESTED** [review]
You need to do this in map and mod upload. Unless there are different requirements for map and mod (which I am not aware of), the actual regex should be extracted to a dedicated method and called by all upload services.

I recall that this is already done somewhere, but I can't find it. Maybe it was in the java api instead.

**Comment by 1-alex98** [comment]
@Brutus5000 made a PR for java-api, but there will still be maps that have an incorrect syntax what do you wann do with them??

**Comment by Brutus5000** [comment]
Looks like we need a script on the server to rename the file and update the sql table entry. But we will probably forget this. Where could we make in issue for that? ^^

**Comment by 1-alex98** [comment]
At least we need to do something as map vault crashes on illegal characters !

**Comment by 1-alex98** [comment]
So what is the outcome of all of this?

**Comment by Brutus5000** [comment]
May general feedback is still the same. Validate the filename consistently over maps and mods.

**Comment by 1-alex98** [comment]
So I close this?

**Pull request closed without merging**
