### PR TITLE
Remove Account settings

### LINKED ISSUE #1469: Restructure account tab in settings
The account tab is none functional and anyways we want to have all account options on the website. Just remove the tab.

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #1469

### CODE REVIEW

**Review by Geosearchef — DISMISSED** [review]
please squash commits, "remove the rest" is not a good commit message, maybe also reference the issue

**Review by Brutus5000 — COMMENTED** [review]
I am missing a change to remove the account management OAuth scope. Did I oversee it?

**Comment by 1-alex98** [comment]
That needs to be done in the database

**Comment by 1-alex98** [comment]
grafik

**Review by Brutus5000 — APPROVED** [review]

**Pull request merged**
