### PR TITLE
Replace topic instead of append

### LINKED ISSUE #1486: Chat Channel topic appended when changed instead of replaced

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #1486

### CODE REVIEW

**Comment by Brutus5000** [comment]
I would like to see a message that the topic has changed.

**Comment by 1-alex98** [comment]
Where?

**Comment by 1-alex98** [comment]
Can we have a seperate issue tho instead of putting it in the bug fix

**Comment by 1-alex98** [comment]
needs review or will need to megre any way

**Review by Brutus5000 — APPROVED** [review]

**Pull request merged**
