### PR TITLE
increase map generation timeout, fix mapGen join, preview image

### PR DESCRIPTION
**Pull request by Geosearchef**

### CODE REVIEW

**Review by Brutus5000 — DISMISSED** [review]
Is there any visual feedback that the map is being generated?

**Comment by Geosearchef** [comment]
There's a loading bar and the spinner in the bottom bar.

**Review by Brutus5000 — APPROVED** [review]

**Review by Brutus5000 — DISMISSED** [review]
Fix tests first

**Review by Brutus5000 — DISMISSED** [review]

**Review by 1-alex98 — APPROVED** [review]

**Comment by 1-alex98** [comment]
Please always make an issue @Geosearchef and if it is an issue with only a title

**Pull request merged**
