### PR TITLE
Remove cookie service

### PR DESCRIPTION
**Pull request by Sheikah45**
In prefs the cookies cause an illegal reflective action to occur which is preventing us from using java16. Cookies are only used by the unitdb  Controller and from what I can tell no relevant cookies to the db are actually stored making it rather useless.

### CODE REVIEW

**Comment by 1-alex98** [comment]
It was supposed to store the unit db settings... Don't ask me if it actually still works :D

**Comment by 1-alex98** [comment]
Anyways its functionality is not that relevant

**Review by 1-alex98 — APPROVED** [review]

**Comment by Sheikah45** [comment]
Yeah it seems like the type of db is stored in the preferences itself

**Comment by 1-alex98** [comment]
No it was the settings of @Rackover 's unit db

**Comment by Rackover** [comment]
if I remember correctly you can pass these settings as a string in a GET parameter, but I may be wrong :) 
https://github.com/FAForever/UnitDB/blob/master/index.php#L32 Check it out

Have a nice day ♥

**Comment by 1-alex98** [comment]
Yeah no idea it is good the cookie service is gone probably

**Pull request merged**
