### PR TITLE
Show panel if needed permission are given

### LINKED ISSUE #1524: Moderation panel not shown since new permission system
Implement new system

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #1524

### CODE REVIEW

**Comment by 1-alex98** [comment]
So we will just go with a permission for kicking users which the server ignores/does not know. But when we giv it to all mods(the moderation) group that should be fine. Well some other time the server can be changed to respect the new Permission System.

**Comment by 1-alex98** [comment]
TODO: Use correct string from @Brutus5000 PR https://github.com/FAForever/server/pull/509/files

**Comment by 1-alex98** [comment]
In sync with server PR only that server pr is not ready yet

**Comment by 1-alex98** [comment]
@Brutus5000 I need a review here... I made u the required db migration for the server

**Comment by 1-alex98** [comment]
The server access token stuff will be placed on top of this. Because this also needs to know stuff about current user.

**Review by Brutus5000 — CHANGES_REQUESTED** [review]
The MeResult should be taken from faf-java-commons (needs update)

**Comment by 1-alex98** [comment]
The server PR got merged

**Comment by 1-alex98** [comment]
I wanna make the switch to faf comoons in a different PR

**Pull request merged**
