### PR TITLE
Added vault/mods filtering by uploader's login

### PR DESCRIPTION
**Pull request by salvationFPS**

### CODE REVIEW

**Review by Geosearchef — CHANGES_REQUESTED** [review]
Please do only modify the english i18n file. The others are generated from POEditor.

**Comment by salvationFPS** [comment]
> Please do only modify the english i18n file. The others are generated from POEditor.

fixed

**Review by 1-alex98 — APPROVED** [review]

**Comment by 1-alex98** [comment]
We have a chat service called Zulip feel free to ask a moderator and join it

**Comment by 1-alex98** [comment]
Please write Fixes #1447 in commit message

**Pull request merged**
