### PR TITLE
Code signing

### PR DESCRIPTION
**Pull request by 1-alex98**
if no CERT_PASSWORD is set or it is empty the executable is not signed...

### CODE REVIEW

**Comment by 1-alex98** [comment]
Can somebody see what happens if u download the self signed release? If it works out ok we might as well self sign the exe for the time being

**Comment by Sheikah45** [comment]
When I run it the windows defender still warns me but I do see the publisher but still have to click the advanced settings to install

**Comment by 1-alex98** [comment]
but it did not get worse right?

**Comment by Sheikah45** [comment]
correct it did not get worse

**Comment by 1-alex98** [comment]
So we can also self sign for the time being

**Comment by 1-alex98** [comment]
Let's keep it for the time being

**Comment by Sheikah45** [comment]
stale

**Pull request closed without merging**
