### PR TITLE
Use available ports for replay server

### LINKED ISSUE #792: Avoid local replay port being blocked by using random free port
java.util.concurrent.CompletionException: java.net.BindException: Address already in use: JVM_Bind
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at com.faforever.client.replay.ReplayServerImpl.lambda$start$2(ReplayServerImpl.java:114)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
	at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
	at java.net.PlainSocketImpl.bind(Unknown Source)
	at java.net.ServerSocket.bind(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at java.net.ServerSocket.<init>(Unknown Source)
	at com.faforever.client.replay.ReplayServerImpl.lambda$start$2(ReplayServerImpl.java:100)
	... 1 more

any ideas to fix, was using the old faf client untill i clean installed the new one.

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #792

### CODE REVIEW

**Review by Geosearchef — DISMISSED** [review]
Sure there is no better way than `new Thread(anon runnable).start()` ?

**Comment by 1-alex98** [comment]
new Thread(anon runnable).start()... I did not code that, and thats not the scope of the Pr I guess

**Comment by Geosearchef** [comment]
It isn't, but still it's ugly ;)

**Comment by 1-alex98** [comment]
Make an issue and I Pr XD

**Comment by Geosearchef** [comment]
#831 :stuck_out_tongue:

**Comment by 1-alex98** [comment]
There is something wrong with travis! It is not the PR

**Comment by micheljung** [comment]
Codacy

**Pull request merged**
