### PR TITLE
Update FafClientApplication.java

### PR DESCRIPTION
**Pull request by Evgene-Kopylov**
Remove default Windows admin check.
It should not bozer regular users

Screenshot 2022-01-03 190818
.

### CODE REVIEW

**Comment by Sheikah45** [comment]
The admin check warning is there to ensure users do not accidentally run the client as admin and mess up the file permissions on the files the client uses and writes to. It will not be removed.

**Comment by Evgene-Kopylov** [comment]
> The admin check warning is there to ensure users do not accidentally run the client as admin and mess up the file permissions on the files the client uses and writes to. It will not be removed.

it disturbs gaming experience. that is critical issue.

**Comment by bukajsytlos** [comment]
can you elaborate? it's one time check. you should not run applications under admin as 99% of users do.

**Comment by Evgene-Kopylov** [comment]
it is not one-time. it pops up every time. 
and there is no easy way, nor reason to fix Win sys settings.

the correct way seems to add "/AdminCheck" as command line parameter instead.

**Comment by bukajsytlos** [comment]
maybe there could be checkbox I understand the risk and I will not bother technical support for breaking client

**Pull request closed without merging**
