### PR TITLE
WIP: Redesign `Create a game` window. Offline mode. Scenarios with ordered missions

### LINKED ISSUE #2372: Allow creating offline games while logged in
**Is your feature request related to a problem? Please describe.**
Allow players to create offline games while logged in from the custom game and coop tabs

### LINKED ISSUE #2870: `Create a game` dialog should be able to handle any type of maps, including coop ones.
image

image

### LINKED ISSUE #2877: Replace all unordered missions with scenarios with ordered missions

### PR DESCRIPTION
**Pull request by Marc-Spector**
Closes #2372 
Closes #2870 
Closes #2877 

The https://github.com/FAForever/fa/pull/4516 PR is required

### CODE REVIEW

**Comment by Sheikah45** [comment]
Why is the skirmish pr required for this? For offline couldn't you just start the game as we do now and just not send the server messages?

**Comment by Marc-Spector** [comment]
https://github.com/FAForever/fa/issues/4514
From part of message from the issue:
The /map argument is not suitable, as it run the match immediately. Some will need to configure the lobby (win conditions, mods, etc.)

**Comment by Marc-Spector** [comment]
> For offline couldn't you just start the game as we do now and just not send the server messages?

Technically, this is no longer an offline game

**Comment by Sheikah45** [comment]
Not sure what you mean? For the offline issue I had created all I really meant was that you could start a game that wouldn't be advertised to other players. Nothing about how we start the game now needs you to be online besides the server communication.

**Comment by Marc-Spector** [comment]
> For the offline issue I had created all I really meant was that you could start a game that wouldn't be advertised to other players.

Where? Could you point out where it is possible to do this?

**Comment by Sheikah45** [comment]
Yes you would just modify the hostGame and startGame functions to remove the calls to the lobby server and the replay server  here https://github.com/FAForever/downlords-faf-client/blob/31ba532b0871b0dc8056f8eb7a8adb2d8e85d199/src/main/java/com/faforever/client/game/GameService.java#L278-L299. So specifically the hostGame function and startGame function.

Start game just takes the game parameters so could be easy to build from a newgameinfo object.

**Comment by Sheikah45** [comment]
Could probably take out the updateifnecessary calls as well to make it truly offline but that might be unnecessary since at this point people have to be logged in and if they are logged in they can update things

**Comment by Marc-Spector** [comment]
Eh... Okay. I'll take a look at it.
I just thought my solution was better. Launched and forgot. No need to change the code related to calls to the lobby server and the replay server. It is just my personal opinion 😃

**Comment by Sheikah45** [comment]
Well you already have to create a separate start game offline method anyway. This method just wouldn't need to introduce something to the game code as well.

**Comment by Sheikah45** [comment]
Since creating the offline calls is just removing stuff from the online methods and not modifying anything really

**Comment by Marc-Spector** [comment]
> Yes you would just modify the hostGame and startGame functions to remove the calls to the lobby server and the replay server here

Unfortunately, there I'm doing something wrong (nothing does not work), or my skills are not enough to implement the offline feature.

Without offline mode, this PR does not make sense.

**Pull request closed without merging**
