### PR TITLE
add report entry to user context menu

### LINKED ISSUE #715: Add "Report abuse" to player context menu
Open this URL in a browser: https://docs.google.com/forms/d/e/1FAIpQLSfeg4ywc4JVC4frnpkPi6udTRpPqti0d4lH1DEmlRhWOnpagg/viewform?c=0&w=1

### PR DESCRIPTION
**Pull request by Geosearchef**
closes #715

### CODE REVIEW

**Review by micheljung — CHANGES_REQUESTED** [review]
I'd prefer to see the URL the application properties
and a unit test would be a quick win

otherwise nice feature :)

**Comment by 1-alex98** [comment]
Can we send additional data to the google doc? like the exception?

**Comment by 1-alex98** [comment]
I checked we can and I think be should do it ;) we can prefill a form with  Username, Client Version, Exception, Time ect.

**Comment by Geosearchef** [comment]
I wanted to and already checked this and telling from an official google website this is not yet implemented. Maybe that site was outdated. Could you link me?

**Comment by 1-alex98** [comment]
Something like this https://docs.google.com/forms/d/e/1FAIpQLScipUzG6Qa6AJK7eh7dWFwrXmxVLHLsnEsu8CxhMGyaospgXQ/viewform?usp=pp_url&entry.1847302185=Client+shows+unexpected+behaviour&entry.1425713905=%3Cuser%3E&entry.1318314325=%3Cclient+version%3E&entry.534292547=%3Cexception%3E

**Comment by 1-alex98** [comment]
Well it is implemted

**Review by 1-alex98 — CHANGES_REQUESTED** [review]
Lets prefill stuff then

**Comment by micheljung** [comment]
@axel1200 this is about reporting users, not client exceptions

**Comment by 1-alex98** [comment]
oh well i got this wrong then, but still you can prefill stuff then and actually https://docs.google.com/forms/d/e/1FAIpQLScipUzG6Qa6AJK7eh7dWFwrXmxVLHLsnEsu8CxhMGyaospgXQ/viewform?usp=pp_url&entry.1847302185=Client+shows+unexpected+behaviour&entry.1425713905=%3Cuser%3E&entry.1318314325=%3Cclient+version%3E&entry.534292547=%3Cexception%3E would be a good solution to report bugs ;) 
Sentry would also be cool, but not sure if we ever gonna implement it....

**Comment by Geosearchef** [comment]
now prefilled, anyone got an idea how to open a browser without HostServicesFactory?

**Comment by 1-alex98** [comment]
has conflicts and test fail

**Comment by Geosearchef** [comment]
Obsolete, should use the new report system.

**Comment by Geosearchef** [comment]
Obsolete, should use the new report system.

**Pull request closed without merging**
