### PR TITLE
Add desktop icon

### LINKED ISSUE #1269: desktop shortcut
pls add a tick box to the install wizard to create a desktop shortcut for the client exe

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #1269

### CODE REVIEW

**Comment by Brutus5000** [comment]
How can I test this?

**Comment by 1-alex98** [comment]
Build an installer locally XD or ask me and i can send u one

**Review by Brutus5000 — APPROVED** [review]
Works fine on Windows 10

**Comment by 1-alex98** [comment]
Well it wont work on linux for sure and it will also work on win 7

**Pull request merged**
