### PR TITLE
Exclude guava from faf-commons

### LINKED ISSUE #1438: Crash on startup
**Describe the bug**
The 0.10.7 client crashes on startup when calling `checkVaultFileSystemLocation`, at https://github.com/FAForever/downlords-faf-client/blob/v0.10.7/src/main/java/com/faforever/client/vault/VaultFileSystemLocationChecker.java#L46

The traceback is the following : 
```
java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: com.github.nocatch.NoCatchException: javafx.fxml.LoadException: 
file:/usr/share/java/downlords-faf-client/lib/downlords-faf-client-0.10.7.jar!/theme/main.fxml

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at com.github.nocatch.NoCatch.wrapException(NoCatch.java:61)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:53)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34)
	at com.faforever.client.theme.UiService.loadFxml(UiService.java:412)
	at com.faforever.client.theme.UiService$$FastClassBySpringCGLIB$$2b0b2208.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.faforever.client.theme.UiService$$EnhancerBySpringCGLIB$$c58fa49b.loadFxml(<generated>)
	at com.faforever.client.FafClientApplication.showMainWindow(FafClientApplication.java:115)
	at com.faforever.client.FafClientApplication.start(FafClientApplication.java:100)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 more
Caused by: javafx.fxml.LoadException: 
file:/usr/share/java/downlords-faf-client/lib/downlords-faf-client-0.10.7.jar!/theme/main.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2625)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2595)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49)
	... 17 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2591)
	... 20 more
Caused by: java.lang.NoSuchMethodError: com.google.common.base.CharMatcher.ascii()Lcom/google/common/base/CharMatcher;
	at com.faforever.client.vault.VaultFileSystemLocationChecker.checkVaultFileSystemLocation(VaultFileSystemLocationChecker.java:46)
	at com.faforever.client.main.MainController.initialize(MainController.java:196)
	... 32 more
```

Manually editing the `client.prefs` to set `forgedAlliance.vaultCheckDone` to `true` bypasses the code block and the client successfully launches, but I'm not sure whether this causes problems or not.

**OS**
Linux

### PR DESCRIPTION
**Pull request by 1-alex98**
Fixes #1438

### CODE REVIEW

**Comment by Brutus5000** [comment]
This would potentially break faf-java-commons then.

**Comment by 1-alex98** [comment]
Hmm why? We have guava in our peoject anyway and till now faf-commons ran with the clients guava just fine...

**Comment by Brutus5000** [comment]
The irony here is that the guava version in faf-java-commons is the *newer* one. And the error in #1438 should not happen as the method exists in both versions.

**Comment by Katharsas** [comment]
Maybe some other dependency of faf-java-commons pulls in an older version.

**Comment by 1-alex98** [comment]
Then lets keep excluding it and update guava version

**Comment by 1-alex98** [comment]
or shade it in faf-commons

**Comment by 1-alex98** [comment]
What did we agree on @Brutus5000 🤔

**Comment by Brutus5000** [comment]
Exclude it but update to latest version

**Comment by 1-alex98** [comment]
ok

**Pull request merged**
