### PR TITLE
Fix assertion by setting launch before state

### PR DESCRIPTION
**Pull request by 1-alex98**

### CODE REVIEW

**Review by Brutus5000 — CHANGES_REQUESTED** [review]
You are changing behavior without adapting a test and it doesn't break a unit test --> There is a unit test missing.

**Comment by 1-alex98** [comment]
Well there was no test for the order of them...

**Comment by 1-alex98** [comment]
Should i add one?

**Comment by Brutus5000** [comment]
Yes, we should add it 😄

**Review by Brutus5000 — APPROVED** [review]

**Pull request merged**
