### PR TITLE
Show warning on close if forged alliance is still running

### LINKED ISSUE #714: Check if forged alliance is still running when closing client
Warn user if fa is still running and ask him wether to continue...

### PR DESCRIPTION
**Pull request by Geosearchef**
Closes #714

### CODE REVIEW

**Review by micheljung — CHANGES_REQUESTED** [review]
I realized that we're getting sloppy on unit tests. This one should get one :)

**Comment by Geosearchef** [comment]
There is no unit test for WindowController currently.

**Comment by Geosearchef** [comment]
Do you mean we should test the methods that just modify UI or just the methods that user other services?

**Review by 1-alex98 — APPROVED** [review]

**Comment by Geosearchef** [comment]
Test is WIP

**Review by micheljung — APPROVED** [review]

**Comment by micheljung** [comment]
Can you please resolve the conflict, it can then be merged :-)

**Comment by 1-alex98** [comment]
@Geosearchef can you rebase?

**Comment by 1-alex98** [comment]
@Geosearchef would be cool you resolved conflicts the longer you wait the more there are

**Comment by 1-alex98** [comment]
We know use a different window therefore this needs to be redone completely. This then also needs adjustments in the library included for the borderless window

**Pull request closed without merging**
