### PR TITLE
Change installation directory to LocalAppData

### LINKED ISSUE #1951: Install client into LOCALAPPDATA
In preparation to https://github.com/FAForever/downlords-faf-client/issues/1753, change the installation directory to local AppData.

### PR DESCRIPTION
**Pull request by micheljung**
Fixes #1951, #1952

### CODE REVIEW

**Comment by 1-alex98** [comment]
How this behave then? Does it still uninstall old version does it read old installer path?

**Comment by 1-alex98** [comment]
Did you try what Ingo said https://stackoverflow.com/questions/64077801/how-to-change-installation-directory-in-install4j

**Comment by 1-alex98** [comment]
@micheljung should I have a look instead

**Comment by KionX** [comment]
Why LocalAppData?
Why not %USERPROFILE% or %PROGRAMFILES% ?

**Comment by micheljung** [comment]
> Why LocalAppData? Why not %USERPROFILE% or %PROGRAMFILES% ?

`%USERPROFILE%` is a parent directory of `%LOCALAPPDATA%`. Moreover, it's not meant to directly contain installed applications.
`%PROGRAMFILES` is where the client is currently installed into and evaluated permissions are required in order to do so. This continues to cause issues and prevents auto-updating.

`%LOCALAPPDATA%` is the right place for user- and computer-specific applications. Chances are you are using Google Chrome, which is installed there, too.

**Comment by KionX** [comment]
Applications are not installed in LOCALAPPDATA. Only their settings.
USERPROFILE is easier for the user to find.
Google Chrome is installed in PROGRAM FILES.
I think LOCALAPPDATA is an unfortunate choice.

**Comment by Sheikah45** [comment]
One thing to note on this is that the installer no longer requires installation into program files. if a user doesnt have or want to elevate permissions it will install into local app data or they can select the installation location.

Not sure if this changes the status of this pr

**Comment by micheljung** [comment]
> Applications are not installed in LOCALAPPDATA. Only their settings.

Wrong, it's even the [default folder of the Windows Installer](https://docs.microsoft.com/en-us/windows/win32/msi/installation-context) for per-user installations:
image

> Google Chrome is installed in PROGRAM FILES.

If you install it "per user" it's certainly in `%LOCALAPPDATA%`:
image

Just like Discord:
image

Even Microsoft VS Code:
image

Probably `%LOCALAPPDATA%\Programs` is the best choice, but that's still `%LOCALAPPDATA%`

> USERPROFILE is easier for the user to find.

*That* would be an unfortunate choice because it's, as the name suggests, for the user's Profile and not for applications. If "easier for the user to find" was the criteria to select the best directory, then we would install it into `Desktop`. But there are more important things to consider, like access permissions. And that's the main reason why we should no longer install to `%ProgramFiles%` and there is no better location than `%LOCALAPPDATA%`(`/Programs`)

**Comment by Sheikah45** [comment]
stale

**Pull request closed without merging**
