### PR TITLE
Manually add maps

### LINKED ISSUE #1879: Maps not added to map list when added to directory manually
Currently maps that are manually added to the maps directory are not added to the maps list in the client forcing a restart for the map to be recognized

**To Reproduce**
Add a map to the maps directory while the client is open

**Expected behavior**
The client should add the map to the installed maps list

**OS**
Windows

### PR DESCRIPTION
**Pull request by 1-alex98**
Adds watcher for manually added maps
Fixes #1879

### CODE REVIEW

**Comment by Sheikah45** [comment]
taking credit for my work :P
I kid

**Comment by 1-alex98** [comment]
👍 but i have the t-shirt already

**Comment by 1-alex98** [comment]
I fucked up while force pushing :D because of the vcs.xml thing

**Comment by Sheikah45** [comment]
yeah that vcs.xml thing makes a lot of stuff hard. Dont know why it is in the repo.

**Pull request merged**
