### PR TITLE
Resolve #2855 and #2856

### LINKED ISSUE #2855: The button of client in window taskbar does not flash after successful login

### LINKED ISSUE #2856: Does not display by default the first selected game in the game details window after launching the client

### PR DESCRIPTION
**Pull request by Marc-Spector**
Closes #2855 
Closes #2856

### CODE REVIEW

**Comment by Marc-Spector** [comment]
Fixed error messages when updating the topic if try to reconnect the chat

```
java.lang.IllegalArgumentException: Chat user 'DaphnewenSiwaona' is unknown for channel '#russian'
	at com.faforever.client.chat.KittehChatService.lambda$getOrCreateChatUser$9(KittehChatService.java:203)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at com.faforever.client.chat.KittehChatService.getOrCreateChatUser(KittehChatService.java:203)
	at com.faforever.client.chat.ChannelTabController.getMessageCssClass(ChannelTabController.java:302)
	at com.faforever.client.chat.AbstractChatTabController.renderHtml(AbstractChatTabController.java:627)
	at com.faforever.client.chat.AbstractChatTabController.appendChatMessageSection(AbstractChatTabController.java:577)
	at com.faforever.client.chat.AbstractChatTabController.addMessage(AbstractChatTabController.java:539)
	at com.faforever.client.chat.AbstractChatTabController.lambda$onChatMessage$22(AbstractChatTabController.java:507)
	at com.faforever.client.fx.JavaFxUtil.runLater(JavaFxUtil.java:484)
	at com.faforever.client.chat.AbstractChatTabController.onChatMessage(AbstractChatTabController.java:506)
	at com.faforever.client.chat.ChannelTabController.updateChannelTopic(ChannelTabController.java:218)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:833)

java.lang.IllegalArgumentException: Chat user 'Tex' is unknown for channel '#aeolus'
	at com.faforever.client.chat.KittehChatService.lambda$getOrCreateChatUser$9(KittehChatService.java:203)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at com.faforever.client.chat.KittehChatService.getOrCreateChatUser(KittehChatService.java:203)
	at com.faforever.client.chat.ChannelTabController.getMessageCssClass(ChannelTabController.java:302)
	at com.faforever.client.chat.AbstractChatTabController.renderHtml(AbstractChatTabController.java:627)
	at com.faforever.client.chat.AbstractChatTabController.appendChatMessageSection(AbstractChatTabController.java:577)
	at com.faforever.client.chat.AbstractChatTabController.addMessage(AbstractChatTabController.java:539)
	at com.faforever.client.chat.AbstractChatTabController.lambda$onChatMessage$22(AbstractChatTabController.java:507)
	at com.faforever.client.fx.JavaFxUtil.runLater(JavaFxUtil.java:484)
	at com.faforever.client.chat.AbstractChatTabController.onChatMessage(AbstractChatTabController.java:506)
	at com.faforever.client.chat.ChannelTabController.updateChannelTopic(ChannelTabController.java:218)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Sheikah45** [comment]
Can I get a more descriptive title?

**Comment by Marc-Spector** [comment]
I cannot think of a more descriptive title. Should I split the PR into several parts?

**Comment by Sheikah45** [comment]
No I guess I can just come up with something when I merge it

**Review by Sheikah45 — DISMISSED** [review]

**Comment by Sheikah45** [comment]
Can you fix the conflicts?

**Comment by Marc-Spector** [comment]
Rebased and resolved the conflicts

**Review by Sheikah45 — APPROVED** [review]

**Comment by Marc-Spector** [comment]
I did not know it was possible to use such the title. 😅

**Pull request merged**
