### PR TITLE
Rebrand the client

### LINKED ISSUE #1233: Debrand the client
This client is now the official faf client. There's no reason anymore like there was in the first place to integrate a player's username into the client name. Technically that will probably stay, but a lot of users are confused by the client's name.

### PR DESCRIPTION
**Pull request by 1-alex98**
Fix #1233

### CODE REVIEW

**Review by Brutus5000 — CHANGES_REQUESTED** [review]
Run a full search on the client plz. I already found and there is even more (e.g. in the build.gradle)
InitSessionMessage line 6
messages.properties line 651
application.yaml line 46

**Comment by Geosearchef** [comment]
Revert compiler.xml, modules.xml, faf client prod.xml

**Comment by 1-alex98** [comment]
> Revert compiler.xml, modules.xml, faf client prod.xml

No they are broken/wrong since a long time

**Review by Geosearchef — APPROVED** [review]

**Comment by 1-alex98** [comment]
This needs further investigation on what certain things do

**Comment by micheljung** [comment]
Do you really want to call the client (and everything, like log files) "Official FAF Client" rather than just "FAF Client"?

**Comment by 1-alex98** [comment]
Well not sure

**Comment by Rackover** [comment]
FAF client is better than Official Faf Client I think, but thats just my opinion

**Pull request closed without merging**
