### PR TITLE
hide ice adapter info window, bump adapter to v2.4.1

### PR DESCRIPTION
**Pull request by Geosearchef**

### CODE REVIEW

**Comment by 1-alex98** [comment]
But what if ice adpter does not terminate how do i close it (Taskmanager ??)

**Comment by 1-alex98** [comment]
Also ho do i turn it on?

**Comment by Geosearchef** [comment]
The ice adapter now has a tray icon, that signals it is still running and when clicked opens the info window able to kill it and show the debug window. (which can also send notifications to your system)

**Comment by 1-alex98** [comment]
ok cool

**Review by 1-alex98 — APPROVED** [review]

**Review by Katharsas — COMMENTED** [review]
~~I dont see a tray icon appearing (Win 10)~~
Ok i do get the tray icon (and a nice windows notification when it starts). However clicking it does nothing.

**Comment by Geosearchef** [comment]
Is java fx available?

**Comment by 1-alex98** [comment]
Probably not he uses jdk 11

**Review by Katharsas — COMMENTED** [review]
Yeah. Whatever i guess thats not really client issue anyway. You might need to think about this though if switching to JDK 11 becomes a thing. And for the Linux people that dont use the Oracle JDK.

**Review by Katharsas — APPROVED** [review]

**Comment by 1-alex98** [comment]
Yeah @Geosearchef we need to either apply the workarround we did in the client or u go modular

**Pull request merged**
