### PR TITLE
Add click to zoom to create game map preview

### LINKED ISSUE #2642: Add ability to zoom a map in `create game` window

### PR DESCRIPTION
**Pull request by Marc-Spector**
Closes #2642
https://forum.faforever.com/topic/3643/zoom-map-when-hosting by phong

demo1

### CODE REVIEW

**Review by Sheikah45 — DISMISSED** [review]

**Comment by Garanas** [comment]
I can not see a typical interaction animation when you hover over the map. As an example, take the any button here on Github that gets slightly darker when you hover over it. I think it would make the user experience better if it did have that.

**Comment by Marc-Spector** [comment]
Unfortunately, JavaFx CSS does not support animation.

**Comment by Garanas** [comment]
Could you add another texture on top (that makes it slightly darker, 10% alpha) when you hover over it? Because otherwise it feels like a hidden feature that you only find out about on accident

**Comment by Marc-Spector** [comment]
It didn't work out for me. 😢

**Comment by Marc-Spector** [comment]
Maybe someone more experienced can do it.

**Comment by BlackYps** [comment]
you should be able to add a different style on hover by appending :hover to the classname in css

**Comment by Sheikah45** [comment]
I added an overlay that will highlight things when hovered.

ezgif-4-c269e2bfb5

**Review by Sheikah45 — APPROVED** [review]

**Comment by Marc-Spector** [comment]
I figured out why it didn't work for me. ImageView does not support all CSS properties. The `background-color` property did not work. Thanks for adding this.

**Pull request merged**
