### PR TITLE
Add vm options to bootRun

### LINKED ISSUE #1443: Gradle task downloadNativeDependencies downloads to wrong folder
- This task copies native dependencies into `/build/resources/native` whereas the task `gradle bootRun` expects them to be in `/lib`. This means that in an IDE (except IntelliJ?) or when only using gradle without IDE, you need to copy around the native files manually before being able to run the client.

- This task should be a dependency of any task that runs the client (like `bootRun`) so that it doesn't need to be executed manually. (DONE)

### PR DESCRIPTION
**Pull request by Sheikah45**
Closes #1443 and #1546

### CODE REVIEW

**Review by Katharsas — DISMISSED** [review]
Yep that fixed both issues, nice.

**Comment by micheljung** [comment]
I advise against using Gradle to run because it takes way more time to launch.

**Comment by Sheikah45** [comment]
In what situation does it take more time to launch? I did not experience this in my testing

**Comment by Sheikah45** [comment]
Running on my machine after all the tasks are run once they seem comparable in time to start up

BootRun: 3.8 secs

<details>
<summary>Details</summary>

```
6:41:24 AM: Executing task 'bootRun'...


> Configure project :
Platform is: win

> Task :downloadIceAdapter UP-TO-DATE
Download https://github.com/FAForever/java-ice-adapter/releases/download/v3.1.1/faf-ice-adapter.jar

> Task :downloadUnixUid
Download https://github.com/FAForever/uid/releases/download/v4.0.4/faf-uid

> Task :downloadWindowsUid UP-TO-DATE
Download https://github.com/FAForever/uid/releases/download/v4.0.4/faf-uid.exe

> Task :downloadNativeDependencies
> Task :processResources UP-TO-DATE
> Task :webview-patch:compileJava UP-TO-DATE
> Task :webview-patch:processResources NO-SOURCE
> Task :webview-patch:classes UP-TO-DATE
> Task :webview-patch:jar UP-TO-DATE
> Task :webview-patch:assemble UP-TO-DATE
> Task :webview-patch:compileTestJava NO-SOURCE
> Task :webview-patch:processTestResources NO-SOURCE
> Task :webview-patch:testClasses UP-TO-DATE
> Task :webview-patch:test NO-SOURCE
> Task :webview-patch:check UP-TO-DATE
> Task :webview-patch:build UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :classes UP-TO-DATE

> Task :bootRun
06:41:27.835 [main] DEBUG com.faforever.client.preferences.PreferencesService - Logger initialized
```

</details>

Main Task: 4.4 secs

<details>
<summary>Details</summary>

```
6:41:37 AM: Executing task 'Main.main()'...


> Configure project :
Platform is: win

> Task :downloadIceAdapter UP-TO-DATE
Download https://github.com/FAForever/java-ice-adapter/releases/download/v3.1.1/faf-ice-adapter.jar

> Task :downloadUnixUid
Download https://github.com/FAForever/uid/releases/download/v4.0.4/faf-uid

> Task :downloadWindowsUid UP-TO-DATE
Download https://github.com/FAForever/uid/releases/download/v4.0.4/faf-uid.exe

> Task :downloadNativeDependencies
> Task :processResources UP-TO-DATE
> Task :webview-patch:compileJava UP-TO-DATE
> Task :webview-patch:processResources NO-SOURCE
> Task :webview-patch:classes UP-TO-DATE
> Task :webview-patch:jar UP-TO-DATE
> Task :webview-patch:assemble UP-TO-DATE
> Task :webview-patch:compileTestJava NO-SOURCE
> Task :webview-patch:processTestResources NO-SOURCE
> Task :webview-patch:testClasses UP-TO-DATE
> Task :webview-patch:test NO-SOURCE
> Task :webview-patch:check UP-TO-DATE
> Task :webview-patch:build UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :classes UP-TO-DATE

> Task :Main.main()
06:41:41.466 [main] DEBUG com.faforever.client.preferences.PreferencesService - Logger initialized
```

</details>

**Comment by micheljung** [comment]
You don't see the difference because you didn't set this:

image

Therefore, your IDE always started via Gradle - mine did not. But with the changed run configuration it would :)

**Comment by Sheikah45** [comment]
Ah yes there are also issues for some people when they build and run using intellij IDEA. We have only been able to get consistent builds using gradle and I believe the current setup docs say to use gradle as well. At least that is what Alex told me when I started.

**Comment by Sheikah45** [comment]
But we can have the run configurations use the application route since they are in the idea specific folder anyway

**Comment by Sheikah45** [comment]
I had only changed that to try and reduce duplication of the jvm arguments as I wasn't aware of a way to reference the ones added to the bootRun

**Comment by Sheikah45** [comment]
Also it seems like if you use the spring based start it always bypasses gradle anyway. But I am not sure if that is only available in Intellij Ultimate

**Pull request merged**
