### PR TITLE
Use Default Decorator

### LINKED ISSUE #1317: missing command line switch
If a user deletes the "%s" in the command line switch field in the client settings they effectively break the client -> following error will appear upon hosting/joining a game after that:

```
java.util.concurrent.CompletionException: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "/init" (in directory "C:\ProgramData\FAForever\bin"): CreateProcess error=2, The system cannot find the file specified
```

Please don't allow users to break the client by removing the content of the command line switch field

### PR DESCRIPTION
**Pull request by 1-alex98**
Fix #1317

### CODE REVIEW

**Comment by Katharsas** [comment]
Btw. i think i changed stuff some time ago so you don't need the `"` around `%s` anymore.

**Comment by 1-alex98** [comment]
I thought so as well but it was not

**Comment by Katharsas** [comment]
What?
Tests at least work without `"`, see LaunchCommandBuilderTest line 20.
and see ` @Test
  public void testCommandFormatWithSpaces()`

**Comment by 1-alex98** [comment]
Sorry I thought the thing I was trying to solve here. I missread your comment :D

**Pull request merged**
