### PR TITLE
Fix showing empty rating at some points in time in rating chart

### LINKED ISSUE #2548: The rating is not displayed at some points in time in rating chart
Hover the mouse over the point where the line goes up or down sharply

Examples:
image
image

### PR DESCRIPTION
**Pull request by Marc-Spector**
Closes #2548

### CODE REVIEW

**Comment by Marc-Spector** [comment]
The only X point that will not display the rating is 0.

**Comment by Sheikah45** [comment]
This as implemented changes the date that the points on the graph are associated with which is not desirable.

Screenshot 2022-01-30 080023
Screenshot 2022-01-30 075948

**Review by Sheikah45 — CHANGES_REQUESTED** [review]
See above comment about changing date

**Comment by Marc-Spector** [comment]
I have not changed the code associated with the date. In the picture that you showed, I don't see any deviations. Everything is displayed correctly.

**Comment by Marc-Spector** [comment]
I checked the chart of the other 5 players. It's all right.

**Comment by Sheikah45** [comment]
I will double check but in the picture it shows the same date with different rating values. It might have been an overlap but I thought it wasn't. But will check again.

**Comment by Marc-Spector** [comment]
This is the expected behavior. This means that the player played several games that day. Please look at the chart for the last month (not all the time) for any player.

**Comment by Marc-Spector** [comment]
@Sheikah45  Could you review the PR?

**Comment by Sheikah45** [comment]
Yes I wanted to do another indepth check to make sure the data points don't change but haven't gotten around to it yet

**Review by Sheikah45 — APPROVED** [review]

**Pull request merged**
