### PR TITLE
hide old context menu when new one created

### LINKED ISSUE #1218: User context menu opens multiple times
Right clicking a user multiple times opens multiple context menus.

### PR DESCRIPTION
**Pull request by Geosearchef**
closes #1218

### CODE REVIEW

**Review by Brutus5000 — COMMENTED** [review]
Why would we want to create a new one if we have a reference on the old one? Can we not just move the existing one?

**Comment by Geosearchef** [comment]
right, implemented, I've also switched to a weak reference to not keep referencing all the context menus ever created.

**Comment by 1-alex98** [comment]
You tested it?

**Review by 1-alex98 — APPROVED** [review]

**Comment by Geosearchef** [comment]
yes, of course

**Review by Brutus5000 — COMMENTED** [review]
Please do not introduce a new codestyle (lombok val) without talking to anyone.

**Comment by 1-alex98** [comment]
Did not notice.... @Geosearchef java 10 also offers var but we neither want val nor var...

**Pull request merged**
