### PR TITLE
Add retry to 503 api status and map errors properly

### LINKED ISSUE #1061: Make calls against API resilient
If we make calls against the API running into errors due to the API being down due to restart (deployment of new version). It's not a good user experience to fail on first try and show some stacktrace to the user.

Spring Retry offers mechanics to automatically retry failed calls in a configurable time span. Unresolvable errors can be globally catched.

### LINKED ISSUE #1082: No error handling for bad api requests
```ID     contains     9063317```
Searching replay vault with query `id=="*9063317*"` returns a 'bad request' from the API which is not handled gracefully. It should display some sort of user friendly error like 'This search is invalid please try again with different criteria' instead of dumping the exception trace.

Or even better, the client should not allow the user to perform this query. This may not be easy to implement in general though.

I would consider this a sub-task of #1061

```
java.util.concurrent.CompletionException: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:279)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:79)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:97)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:79)
	at com.faforever.client.api.JsonApiErrorHandler.handleError(JsonApiErrorHandler.java:31)
	at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:172)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:735)
	at org.springframework.security.oauth2.client.OAuth2RestTemplate.doExecute(OAuth2RestTemplate.java:128)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:669)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:310)
	at com.faforever.client.api.FafApiAccessorImpl.getPage(FafApiAccessorImpl.java:587)
	at com.faforever.client.api.FafApiAccessorImpl.getPage(FafApiAccessorImpl.java:574)
	at com.faforever.client.api.FafApiAccessorImpl.findReplaysByQuery(FafApiAccessorImpl.java:322)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206)
	at com.sun.proxy.$Proxy61.findReplaysByQuery(Unknown Source)
	at com.faforever.client.remote.FafService.findReplaysByQuery(FafService.java:299)
	at com.faforever.client.remote.FafService$$FastClassBySpringCGLIB$$6c91c77e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
	... 4 more

```

### LINKED ISSUE #2384: Map and mod upload errors not properly displayed
Currently map and mod upload errors are displayed to the user as a general 422 u processable entity error. The response from the server does contain more useful information in the form of a json API error message. However currently the API accessor does not parse the response as json API resulting in this information not being properly communicated.

It would be best if the error was parsed and displayed properly.

### PR DESCRIPTION
**Pull request by Sheikah45**
Closes #1061
Closes #1082
Closes #2384

### CODE REVIEW

**Comment by micheljung** [comment]
We shouldn't retry on 404 because then, calls to non-existing API paths would be retried which makes no sense.

See https://github.com/FAForever/downlords-faf-client/issues/1061#issuecomment-939289147

**Comment by Brutus5000** [comment]
Not in FAF. 404 can occur if the API is restarting. The container goes down for a moment and Traefik will declare all calls to the api as 404 until the new API is up and running.

**Comment by Sheikah45** [comment]
Also this is currently set to retry only a maximum of 3 times and use an exponential backoff of 5 seconds

**Comment by Brutus5000** [comment]
Which wouldn't be enough to survive an API restart...

**Comment by Sheikah45** [comment]
Well how long is enough?

**Comment by Brutus5000** [comment]
1 minute in total

**Comment by Sheikah45** [comment]
I will use a 30 second exponential backoff then

**Comment by Sheikah45** [comment]
Changed it to a 5 second back off with 5 retries so that it will wait a max of around 2 minutes

**Comment by Brutus5000** [comment]
Ok the services will now throw 503 instead of 404 when they are down (see https://github.com/FAForever/faf-stack/pull/188)

**Comment by Sheikah45** [comment]
Sounds good I will change it to only retry on 503

**Pull request merged**
