### PR TITLE
Feature/#1799 Map Vault Pagination

### LINKED ISSUE #1660: Improve map vault pagination
Currently this is what we have: 

And something like this is the standard:  

Would be nice to have this added for improved vault usability.

### LINKED ISSUE #1799: Use proper pagination in Map vault
JavaFX provides a [Pagination Control](https://docs.oracle.com/javafx/2/ui_controls/pagination.htm).
It's very simple to use and should be used instead of our custom implementation in the map vault.

Other paginations should not be updated as part of this issue.

### PR DESCRIPTION
**Pull request by Sheikah45**
Create Pagination for Map Vault

### CODE REVIEW

**Comment by Sheikah45** [comment]
Need to update Unit Tests

**Comment by 1-alex98** [comment]
Nice, so there are 3 ppl that did pagination in the vault. And I like the one the most in the mod vault. maybe you can look at what they did and make adjust yours in this way.

**Comment by Sheikah45** [comment]
Will take a look and adjust

**Comment by 1-alex98** [comment]
Sorry meant online replays https://github.com/FAForever/downlords-faf-client/pull/1808/files They also know the total number of pages.

**Comment by 1-alex98** [comment]
Should also be able to merge theirs soon, after I have a final look. But it seems pretty well done.

**Comment by Sheikah45** [comment]
taken care of by #1845

**Pull request closed without merging**
